### ISSUE TITLE
Exception in thread DatabasePainter. 

### ISSUE THREAD

**Issue by RobertBuhren** [gaasedelen/lighthouse#50]
Hi all,
I get the following exception when I try to load a overage file:

```
[Lighthouse] Successfully loaded 1 coverage file(s)...
Exception in thread DatabasePainter:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/robert/repo/ida-7.2/plugins/lighthouse/painting/painter.py", line 400, in _async_database_painter
    result = self._paint_database()
  File "/home/robert/repo/ida-7.2/plugins/lighthouse/painting/painter.py", line 295, in _paint_database
    if not self._priority_paint():
  File "/home/robert/repo/ida-7.2/plugins/lighthouse/painting/ida_painter.py", line 413, in _priority_paint
    cursor_address = idaapi.get_screen_ea()
  File "/home/robert/repo/ida-7.2/python/ida_kernwin.py", line 2251, in get_screen_ea
    return _ida_kernwin.get_screen_ea(*args)
RuntimeError: Function can be called from the main thread only
```

The "Coverage Overview" windows is successfully filled with the correct data, however, the disassembly output and the graph view are not painted.

IDA Version: Version 7.2.181105 Linux x86_64 (32-bit address size)

Regards,

Robert

**Comment by gaasedelen** [comment]
Oh cool! Looks like IDA 7.2 may have introduced some thread-safety assertions to the python API's.

I know what it's complaining about and will install 7.2 tonight to test the fix.

Thanks for the report!

**Comment by gaasedelen** [comment]
Hi Robert, I just pushed a fix. When you get a chance, can you please try the fix and confirm it fixes the crash for you?

The fix is one line, so you can punch it in by hand:

https://github.com/gaasedelen/lighthouse/commit/dae71152e484a1dc8638ff973478c0f58bcbee74

Or clone / download / install the development branch:

https://github.com/gaasedelen/lighthouse/tree/develop

Thanks!

**Comment by RobertBuhren** [comment]
Yes, that did the trick!.

Thanks alot for the quick fix.

Regards,
Robert

**Comment by RobertBuhren** [comment]
Btw, I'm using a nice little python script to convert Qemu trace files into drcov trace files that can be read by lighthouse. Maybe this is of interest for some of the lighthouse users. 

You can find it here: https://github.com/RobertBuhren/qemutrace2drcov

Thanks to @domenukk for the initial version of this script.

**Comment by Manouchehri** [comment]
Hmm, not sure if I have a PEBKAC, but after applying dae7115, I’m still having the exact same error with v7.2 on Linux.

**Comment by gaasedelen** [comment]
I botched the fix, it may have been silently failing with the dae7115 patch.

8d60f77 should fix it.

**Comment by gaasedelen** [comment]
@RobertBuhren thanks for the script! I had totally forgotten about qemutrace.

For Lighthouse v0.9 I am hoping to make the coverage/trace loader a bit more diverse (eg, #41). I will look into shipping a qemutrace loader in-box, or may write my own (py2) converter.

**Comment by Manouchehri** [comment]
8d60f77 fixed it for me, thanks!
